services:
  db:
    container_name: genesis-postgres
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    networks:
      - common-net
  db-test:
    container_name: genesis-postgres-tests
    image: postgres:latest
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
    env_file:
      - .env
    networks:
      - common-net
  backend:
    container_name: genesis-blog-backend
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - common-net

networks:
  common-net: { }
